(function() {var implementors = {};
implementors["sos_kernel"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;usize&gt; for <a class='struct' href='sos_kernel/memory/struct.VAddr.html' title='sos_kernel::memory::VAddr'>VAddr</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;*mut T&gt; for <a class='struct' href='sos_kernel/memory/struct.VAddr.html' title='sos_kernel::memory::VAddr'>VAddr</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;*const T&gt; for <a class='struct' href='sos_kernel/memory/struct.VAddr.html' title='sos_kernel::memory::VAddr'>VAddr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='type' href='sos_kernel/arch/cpu/interrupts/idt/type.Handler.html' title='sos_kernel::arch::cpu::interrupts::idt::Handler'>Handler</a>&gt; for <a class='struct' href='sos_kernel/arch/cpu/interrupts/idt/struct.Gate.html' title='sos_kernel::arch::cpu::interrupts::idt::Gate'>Gate</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;*const u8&gt; for <a class='struct' href='sos_kernel/arch/cpu/interrupts/idt/struct.Gate.html' title='sos_kernel::arch::cpu::interrupts::idt::Gate'>Gate</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;u64&gt; for <a class='struct' href='sos_kernel/memory/struct.PAddr.html' title='sos_kernel::memory::PAddr'>PAddr</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;*mut T&gt; for <a class='struct' href='sos_kernel/memory/struct.PAddr.html' title='sos_kernel::memory::PAddr'>PAddr</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;*const T&gt; for <a class='struct' href='sos_kernel/memory/struct.PAddr.html' title='sos_kernel::memory::PAddr'>PAddr</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
